- npm publish 2016.2.2 - implement api POST /pet/{petId}/uploadImage - fix Uncaught TypeError: this.trigger is not a function - fix curl example missing body - add multipart/form-data ability to swgg.apiAjax - add function swgg.collectDocRandomCreate to create random collectDoc - merge crudFileUploadOneByForm into crudFileUploadManyByForm - add function swgg.urlBaseGet - cover example.js